name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8 # or whatever pnpm version you're using

      - uses: actions/setup-node@v4
        with:
          node-version: 20 # or your desired Node.js version
          cache: pnpm

      - run: pnpm install

      - run: pnpm lint
